food_img_path = "maps/10_10_food_map.png"
home_img_path = "maps/10_10_home_map.png"
obstacle_img_path = "maps/10_10_obstacle_map.png"
robot_img_path = "maps/10_10_robot_map_6_bots.png"
robot_personality_list = [1, 1, 1, 2, 2, 2]
perception_range = 3
battery_size = 60
heading_size = 8
policy_filepath_list = []
v_filepath_list = []
q_filepath_list = []
arbitration_type_list = []
num_time_steps = 100
num_monte_carlo_trials = 1
num_threads = 1
results_filename = "results/test_24_swarm_diverse_no_local_model_0_results.npz"
