food_img_path = "maps/25_25_food_map_a.png"
home_img_path = "maps/25_25_home_map.png"
obstacle_img_path = "maps/25_25_obstacle_map.png"
robot_img_path = "maps/25_25_robot_map_1_bot.png"
robot_personality_list = [16]
perception_range = 2
battery_size = 50
heading_size = 8
policy_filepath_list = []
v_filepath_list = []
q_filepath_list = []
arbitration_type_list = []
use_prev_exp = False
save_prev_exp = True
recursive_prev_exp = False
prev_exp_filepath = "recorded_data/gd_indiv_prev_exp_8_trials_map_a.npz"
num_time_steps = 300
heading_change_times = []
num_monte_carlo_trials = 8
num_threads = 1
food_respawn = False
food_pushing = True
enable_terminal_condition = False
results_filename = "results/foraging81.npz"
plot_label = "Model 0"
human_description = "25x25, map a, 1 bot, per range 2, 8 prev trials, gd train indiv"
