food_img_path = "maps/25_25_food_map_d.png"
home_img_path = "maps/25_25_home_map_d.png"
obstacle_img_path = "maps/25_25_obstacle_map.png"
robot_img_path = "maps/25_25_robot_map_d_4_bots.png"
robot_personality_list = [16, 16, 16, 16]
#robot_personality_list = [16, 16, 16, 16, 16, 16, 16, 16]
#robot_personality_list = [16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16]
perception_range = 3
battery_size = 50
heading_size = 8
policy_filepath_list = []
v_filepath_list = []
q_filepath_list = []
arbitration_type_list = []
use_prev_exp = False
prev_exp_filepath = ""
num_time_steps = 300
heading_change_times = [150]
num_monte_carlo_trials = 1
num_threads = 1
food_respawn = False
food_pushing = False
enable_terminal_condition = False
results_filename = "results/test_swarm_local_results.npz"
